apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genieacs

resources:
  - ../../base
  - configmap.yaml
  - genieacs-deployment.yaml
  - genieacs-service.yaml
  - nginx-nbi-auth.yaml
  # Uncomment to enable Ingress
  # - ingress.yaml
