apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genieacs-nbi-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # Using Helm chart from repository
    repoURL: https://cepat-kilat-teknologi.github.io/genieacs-stack
    chart: genieacs-nbi-auth
    targetRevision: 0.2.0
    helm:
      releaseName: genieacs
      values: |
        # ===========================================
        # SECRETS CONFIGURATION
        # ===========================================
        # NBI API Key (embedded in nginx ConfigMap)
        nbiAuth:
          enabled: true
          # Generate with: openssl rand -hex 32
          apiKey: "changeme-generate-with-openssl-rand-hex-32"

        # JWT Secret for UI authentication
        secret:
          # Option 1: Provide JWT secret directly (not recommended for production)
          # jwtSecret: "changeme-generate-with-openssl-rand-hex-32"

          # Option 2: Use existing Kubernetes secret (recommended)
          # Create secret first: kubectl create secret generic genieacs-secrets \
          #   --from-literal=GENIEACS_UI_JWT_SECRET=$(openssl rand -hex 32) -n genieacs
          existingSecret: "genieacs-secrets"

        # ===========================================
        # GenieACS Configuration
        # ===========================================
        genieacs:
          replicaCount: 1
          image:
            repository: cepatkilatteknologi/genieacs
            tag: "1.2.13"
            pullPolicy: IfNotPresent

          service:
            type: LoadBalancer
            # Set your LoadBalancer IP
            loadBalancerIP: "10.100.0.250"

            # IP Whitelist - Only these IPs can access the services
            # Add your allowed IPs/CIDRs here
            loadBalancerSourceRanges:
              - "10.0.0.0/8"        # Internal network
              - "192.168.0.0/16"    # Private network
              # - "203.0.113.50/32" # Specific external IP

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"

        # ===========================================
        # MongoDB Configuration
        # ===========================================
        mongodb:
          persistence:
            data:
              size: 20Gi
              # storageClassName: "your-storage-class"
            configdb:
              size: 2Gi

        # ===========================================
        # Application Settings
        # ===========================================
        config:
          uiAuth: "true"
          nodeEnv: "production"

  destination:
    # Change to your production cluster
    # Example: https://k8s-api.your-domain.com:6443
    server: https://kubernetes.default.svc
    namespace: genieacs

  # ===========================================
  # Sync Policy - Manual for Production
  # ===========================================
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    # WARNING: Do NOT enable automated sync for production
    # automated:
    #   prune: true
    #   selfHeal: true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas